name: generate build file

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run go mod tidy
        run: go mod tidy
      - name: Run go build
        run: go build -o swagen
      - name: Run go test
        run: go test ./...
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: swagen
          path: ./

# This workflow will run only on pull requests to the main branch.
# It will build the project, run go test, and generate a binary called swagen.
# The binary will be available in the root of the repository.
# The binary can be downloaded from the Actions tab in the GitHub repository.
# The binary can be used to generate Swagger documentation for Go projects.
