name: generate build file

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21
      - name: Run go mod tidy
        run: go mod tidy
      - name: Run go build
        run: go build -o swagen
      - name: Run go test
        run: go test ./...
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: swagen
          path: ./
  
  update-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: ./artifacts

    - name: Copy artifact files to repo
      run: |
        cp -r ./artifacts/* .

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git add .
        git commit -m "Update files from artifact"

    - name: Push changes
      run: |
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# This workflow will run only on pull requests to the main branch.
# It will build the project, run go test, and generate a binary called swagen.
# The binary will be available in the root of the repository.
# The binary can be downloaded from the Actions tab in the GitHub repository.
# The binary can be used to generate Swagger documentation for Go projects.
